# Generated by Django 4.2.7 on 2024-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_shop_available_time_slot_shop_shop_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="available_time_slot",
            field=models.TextField(default="0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"),
        ),
    ]
