# Generated by Django 4.2.7 on 2024-01-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_shop_available_time_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="profile_image_url",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_detail",
            field=models.TextField(blank=True, default=""),
        ),
    ]
