# Generated by Django 4.2.7 on 2024-01-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_shop_profile_image_url_alter_shop_shop_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="discountedPrice",
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
