# Generated by Django 4.2.9 on 2024-01-10 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_shop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="shop",
        ),
    ]
