# Generated by Django 4.2.7 on 2024-01-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_service_discountedprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="end_time",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.CharField(default="", max_length=20),
        ),
    ]
