# Generated by Django 4.2.9 on 2024-01-11 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_shop_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Apppointment",
            new_name="Appointment",
        ),
    ]
