# Generated by Django 4.2.9 on 2024-01-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rename_apppointment_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="shop_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="shop_id",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="user",
            name="shop_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AddField(
            model_name="appointment",
            name="shop",
            field=models.ForeignKey(
                default=" ", on_delete=django.db.models.deletion.CASCADE, to="api.shop"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                default=" ", on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
