# Generated by Django 4.2.9 on 2024-01-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_appointment_shop_remove_appointment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="shop_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="user_id",
        ),
        migrations.AddField(
            model_name="appointment",
            name="shop",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                default="None",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
    ]
